version: 2
updates:
- package-ecosystem: docker
  directory: /
  schedule:
    interval: daily
  labels:
  - dependencies
- package-ecosystem: pip
  directory: /
  schedule:
    interval: daily
  labels:
  - dependencies
